import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import type { ConfigContext, ExpoConfig } from 'expo/config';

/**
 * Northline, the consumer app (S-97): the single source of both native projects (Continuous Native Generation:
 * android/ and ios/ are generated by `expo prebuild` / EAS Build and never committed). docs/runbooks/mobile.md.
 *
 * Build-time environment (EAS profiles in eas.json, or your shell):
 *   APP_VARIANT               development | preview | production (bundle id, name)
 *   EXPO_PUBLIC_API_URL       https://api.<zone>/api/v1
 *   EXPO_PUBLIC_AUTH_ISSUER   https://auth.<zone>
 *   EXPO_PUBLIC_SITE_ORIGIN   https://<zone> — the consumer web: legal pages, the claimed https redirect and App Links
 *   EXPO_PUBLIC_FIXTURES      1 = the in-app fixture backend (web smoke test, demos); refused for production
 *   EAS_PROJECT_ID, EAS_OWNER the Expo project (from `eas init`)
 *   GOOGLE_SERVICES_JSON      path of the environment's google-services.json (FCM); an EAS file variable, never committed
 *   NL_IOS_BUILD_NUMBER, NL_ANDROID_VERSION_CODE  only for local builds (EAS keeps them remotely)
 */
type Env = Record<string, string | undefined>;

export type Variant = 'development' | 'preview' | 'production';
export const VARIANTS: Readonly<Record<Variant, { id: string; name: string }>> = {
  development: { id: 'ca.northline.app.dev', name: 'Northline (Dev)' },
  preview: { id: 'ca.northline.app.preview', name: 'Northline (Preview)' },
  production: { id: 'ca.northline.app', name: 'Northline' },
};

/**
 * The `mobile-consumer` client's registrations in northline-auth (server/auth application.yml): the reverse-domain
 * scheme for the system-browser sign-in (passkeys, Google, Apple) and the claimed https link on the consumer site,
 * which the in-app sign-in's hand-off lands on (src/auth/handoff.ts). northline-auth matches redirect URIs exactly.
 */
export const SCHEME = 'ca.northline.app';
export const REDIRECT_URI = `${SCHEME}:/oauth2redirect`;
export const HTTPS_REDIRECT_PATH = '/app/oauth2redirect';
export const CLIENT_ID = 'mobile-consumer';
/** Paths of the consumer site this app claims (App Links / Universal Links): its OAuth redirect; S-102 adds deep links. */
export const APP_LINK_PATH_PREFIX = '/app';

/**
 * The marketing version (CFBundleShortVersionString / versionName): package.json's `version` is its one source
 * (`make mobile-version-set`); build numbers are EAS's (`appVersionSource: remote`). docs/runbooks/mobile-release.md.
 */
export const APP_VERSION: string = (JSON.parse(readFileSync(join(__dirname, 'package.json'), 'utf8')) as { version: string }).version;

/** Permission texts (en; fr-CA in locales/fr.json). Store reviewers read them: keep them exact and honest. */
export const PERMISSION_TEXT = {
  locationWhenInUse:
    'Northline uses your location to suggest your delivery address and show the shops and providers that serve it. It is used only while you have the app open and is never shared with businesses.',
  // mobile gaps part 1 (expo-image-picker): photos on a problem report; a pilot's screenshot from the library
  camera: 'Northline uses the camera only when you take a photo to add to a problem report.',
  photos: 'Northline opens your photos only when you choose one to add to a problem report or to pilot feedback.',
} as const;

/**
 * Android permissions the app asks for; what libraries would add and the app does not use is removed from the merged
 * manifest. Location only while the app is open: no background location, no foreground service.
 */
export const ANDROID_PERMISSIONS = [
  'android.permission.INTERNET',
  'android.permission.ACCESS_COARSE_LOCATION',
  'android.permission.ACCESS_FINE_LOCATION',
  // push (S-102/S-103): Android 13+ asks; the app asks at the moment the design chooses, never at launch
  'android.permission.POST_NOTIFICATIONS',
  // mobile gaps part 1: "Take a photo" on a problem report (expo-image-picker's camera); asked at that tap. The photo
  // library needs no permission (the system photo picker), so storage and media permissions stay removed.
  'android.permission.CAMERA',
] as const;
export const ANDROID_BLOCKED_PERMISSIONS = [
  'android.permission.ACCESS_BACKGROUND_LOCATION',
  'android.permission.FOREGROUND_SERVICE',
  'android.permission.FOREGROUND_SERVICE_LOCATION',
  'android.permission.RECORD_AUDIO',
  'android.permission.SYSTEM_ALERT_WINDOW',
  'android.permission.READ_EXTERNAL_STORAGE',
  'android.permission.WRITE_EXTERNAL_STORAGE',
  'android.permission.READ_MEDIA_IMAGES',
  'android.permission.READ_MEDIA_VIDEO',
  'android.permission.READ_MEDIA_AUDIO',
] as const;

/** RN 0.86 / Expo SDK 57 toolchain levels (the same as the courier app). */
export const NATIVE = {
  android: { compileSdkVersion: 36, targetSdkVersion: 36, minSdkVersion: 24, buildToolsVersion: '36.0.0' },
  ios: { deploymentTarget: '16.4' },
} as const;

/** Brand colours for the native splash and icon background: the base tokens, read from @northline/tokens. */
function baseTokens(): { accent: string; bg: string } {
  const json = JSON.parse(readFileSync(join(__dirname, '../../../web/packages/tokens/tokens.json'), 'utf8')) as {
    base: { accent: string; bg: string };
  };
  return json.base;
}

export function resolveVariant(env: Env): Variant {
  return (['development', 'preview', 'production'] as const).find((v) => v === env.APP_VARIANT) ?? 'development';
}

const strip = (url: string) => url.replace(/\/+$/, '');

export function createConfig(env: Env = process.env): ExpoConfig {
  const variant = resolveVariant(env);
  const v = VARIANTS[variant];
  const isDev = variant === 'development';
  const fixtures = env.EXPO_PUBLIC_FIXTURES === '1';
  if (variant === 'production' && fixtures) throw new Error('EXPO_PUBLIC_FIXTURES must not be set for a production build');
  const apiUrl = strip(env.EXPO_PUBLIC_API_URL ?? 'http://localhost:8080/api/v1');
  const authIssuer = strip(env.EXPO_PUBLIC_AUTH_ISSUER ?? 'http://localhost:9000');
  const siteOrigin = strip(env.EXPO_PUBLIC_SITE_ORIGIN ?? 'http://localhost:3000');
  const https = [apiUrl, authIssuer, siteOrigin].every((u) => u.startsWith('https://'));
  if (variant !== 'development' && !fixtures && !https) {
    throw new Error('Preview and production builds need https EXPO_PUBLIC_API_URL, EXPO_PUBLIC_AUTH_ISSUER and EXPO_PUBLIC_SITE_ORIGIN');
  }
  const siteHost = new URL(siteOrigin).host;
  const linkHost = siteOrigin.startsWith('https://') ? siteHost : null; // App Links / Universal Links need https
  const easProjectId = env.EAS_PROJECT_ID ?? '00000000-0000-0000-0000-000000000000';
  const brand = baseTokens();

  return {
    name: v.name,
    slug: 'northline',
    scheme: SCHEME,
    version: APP_VERSION,
    runtimeVersion: { policy: 'fingerprint' },
    updates: { url: `https://u.expo.dev/${easProjectId}`, fallbackToCacheTimeout: 0, checkAutomatically: 'ON_LOAD' },
    orientation: 'portrait',
    userInterfaceStyle: 'light',
    backgroundColor: brand.bg,
    icon: './assets/icon.png',
    // The display name and permission texts in French (InfoPlist.strings); Android shows its own system texts.
    locales: { fr: './locales/fr.json' },
    ios: {
      bundleIdentifier: v.id,
      buildNumber: env.NL_IOS_BUILD_NUMBER || undefined,
      supportsTablet: false,
      config: { usesNonExemptEncryption: false },
      // The claimed https redirect (and S-102's deep links) plus shared credentials (passkeys, once the app has a
      // native passkey module): the consumer site serves apple-app-site-association for these (S-97).
      associatedDomains: linkHost ? [`applinks:${linkHost}`, `webcredentials:${linkHost}`] : [],
      infoPlist: {
        CFBundleAllowMixedLocalizations: true,
        CFBundleLocalizations: ['en', 'fr'],
        NSLocationWhenInUseUsageDescription: PERMISSION_TEXT.locationWhenInUse,
        NSAppTransportSecurity: { NSAllowsArbitraryLoads: false, NSAllowsLocalNetworking: isDev },
      },
      privacyManifests: {
        NSPrivacyTracking: false,
        NSPrivacyTrackingDomains: [],
        NSPrivacyAccessedAPITypes: [
          { NSPrivacyAccessedAPIType: 'NSPrivacyAccessedAPICategoryUserDefaults', NSPrivacyAccessedAPITypeReasons: ['CA92.1'] },
          { NSPrivacyAccessedAPIType: 'NSPrivacyAccessedAPICategoryFileTimestamp', NSPrivacyAccessedAPITypeReasons: ['C617.1'] },
          { NSPrivacyAccessedAPIType: 'NSPrivacyAccessedAPICategorySystemBootTime', NSPrivacyAccessedAPITypeReasons: ['35F9.1'] },
          { NSPrivacyAccessedAPIType: 'NSPrivacyAccessedAPICategoryDiskSpace', NSPrivacyAccessedAPITypeReasons: ['E174.1'] },
        ],
        // Linked to the person, for app functionality only: their account (name, email, phone), the delivery address
        // and location they choose, the push token (device id), orders and bookings, the card (entered in Stripe's
        // sheet), problem reports (and their photos), booking notes. No tracking. Kept equal to store/privacy.json (S-103 release check).
        NSPrivacyCollectedDataTypes: [
          'NSPrivacyCollectedDataTypeName',
          'NSPrivacyCollectedDataTypeEmailAddress',
          'NSPrivacyCollectedDataTypePhoneNumber',
          'NSPrivacyCollectedDataTypePhysicalAddress',
          'NSPrivacyCollectedDataTypePreciseLocation',
          'NSPrivacyCollectedDataTypeUserID',
          'NSPrivacyCollectedDataTypeDeviceID',
          'NSPrivacyCollectedDataTypePurchaseHistory',
          'NSPrivacyCollectedDataTypePaymentInfo',
          'NSPrivacyCollectedDataTypeCustomerSupport',
          'NSPrivacyCollectedDataTypeOtherUserContent',
          // photos on a problem report, a pilot's screenshot (mobile gaps part 1)
          'NSPrivacyCollectedDataTypePhotosorVideos',
        ].map((type) => ({
          NSPrivacyCollectedDataType: type,
          NSPrivacyCollectedDataTypeLinked: true,
          NSPrivacyCollectedDataTypeTracking: false,
          NSPrivacyCollectedDataTypePurposes: ['NSPrivacyCollectedDataTypePurposeAppFunctionality'],
        })),
      },
    },
    android: {
      package: v.id,
      versionCode: env.NL_ANDROID_VERSION_CODE ? Number(env.NL_ANDROID_VERSION_CODE) : undefined,
      adaptiveIcon: { foregroundImage: './assets/adaptive-icon.png', backgroundColor: brand.accent },
      intentFilters: [
        // The system-browser sign-in hands the code back through the reverse-domain scheme (RFC 8252 § 7.1).
        { action: 'VIEW', category: ['BROWSABLE', 'DEFAULT'], data: [{ scheme: SCHEME, path: '/oauth2redirect' }] },
        // The consumer site's /app/… links open the app once assetlinks.json on the site names it (verified App Link).
        ...(linkHost
          ? [{ action: 'VIEW', autoVerify: true, category: ['BROWSABLE', 'DEFAULT'], data: [{ scheme: 'https', host: linkHost, pathPrefix: APP_LINK_PATH_PREFIX }] }]
          : []),
      ],
      permissions: [...ANDROID_PERMISSIONS],
      blockedPermissions: [...ANDROID_BLOCKED_PERMISSIONS],
      allowBackup: false,
      // FCM (push): the environment's Firebase file, given to EAS Build as a file variable (docs/runbooks/push.md).
      // Without it the app builds and runs; it only gets no push token.
      googleServicesFile: env.GOOGLE_SERVICES_JSON || undefined,
    },
    web: { bundler: 'metro', output: 'single' },
    plugins: [
      'expo-router',
      ['expo-secure-store', { configureAndroidBackup: false }],
      'expo-font',
      'expo-localization',
      'expo-web-browser',
      [
        'expo-location',
        {
          locationWhenInUsePermission: PERMISSION_TEXT.locationWhenInUse,
          // false = leave the key out of Info.plist (the plugin would otherwise add generic "Always" and motion texts)
          locationAlwaysAndWhenInUsePermission: false,
          locationAlwaysPermission: false,
          motionUsagePermission: false,
          isIosBackgroundLocationEnabled: false,
          isAndroidBackgroundLocationEnabled: false,
          isAndroidForegroundServiceEnabled: false,
        },
      ],
      // Photos (mobile gaps part 1): the system photo picker and the camera, with our texts; no microphone (no video)
      ['expo-image-picker', { photosPermission: PERMISSION_TEXT.photos, cameraPermission: PERMISSION_TEXT.camera, microphonePermission: false }],
      // Push (S-102's registration in @northline/mobile-kit): the native module, the aps-environment entitlement
      // (production APNs for store builds) and the Android channel `updates` the worker sends to.
      ['expo-notifications', { mode: isDev ? 'development' : 'production', defaultChannel: 'updates', color: brand.accent, enableBackgroundRemoteNotifications: false }],
      ['expo-splash-screen', { image: './assets/splash-icon.png', imageWidth: 160, resizeMode: 'contain', backgroundColor: brand.bg }],
      [
        'expo-build-properties',
        {
          android: { ...NATIVE.android, enableMinifyInReleaseBuilds: true, enableShrinkResourcesInReleaseBuilds: true, usesCleartextTraffic: isDev },
          ios: { deploymentTarget: NATIVE.ios.deploymentTarget, privacyManifestAggregationEnabled: true },
        },
      ],
    ],
    // tsconfig "paths" only pin React's types; Metro resolves the runtime copies itself (metro.config.js)
    experiments: { typedRoutes: false, tsconfigPaths: false },
    owner: env.EAS_OWNER ?? 'northline',
    extra: {
      apiUrl,
      authIssuer,
      siteOrigin,
      fixtures,
      variant,
      clientId: CLIENT_ID,
      redirectUri: REDIRECT_URI,
      httpsRedirectUri: `${siteOrigin}${HTTPS_REDIRECT_PATH}`,
      eas: { projectId: easProjectId },
    },
  };
}

export default (_ctx: ConfigContext): ExpoConfig => createConfig(process.env);
