-- 2026-10-02 (S-116, Loi 96 readiness): every category of db/seed/categories.json has a French name. V111 named the
-- shop's; this adds the service and food taxonomy (132 rows), so Studio pickers, search facets, the consumer's
-- category pages and the console read French from the database instead of each app keeping its own list. The service
-- names are the consumer web's (web/apps/consumer/src/features/services/taxonomy.ts, FR_NAMES); the food names are
-- new (docs/i18n/translation-review.csv, needs translator review). Data only, additive: a label staff already set in
-- the console (S-94) is kept. No FK, as in V111 (categories may be seeded after the migrations).
INSERT INTO catalogue.category_labels (category_id, lang, name) VALUES
  ('service.automotive', 'fr', 'Automobile'),
  ('service.automotive.mobile-mechanic', 'fr', 'Mécanicien mobile'),
  ('service.automotive.oil-change-and-fluids', 'fr', 'Vidange et liquides'),
  ('service.automotive.brakes-and-suspension', 'fr', 'Freins et suspension'),
  ('service.automotive.tire-change-and-storage', 'fr', 'Changement et entreposage de pneus'),
  ('service.automotive.windshield-repair', 'fr', 'Réparation de pare-brise'),
  ('service.automotive.detailing', 'fr', 'Esthétique automobile'),
  ('service.automotive.battery-boost-and-replacement', 'fr', 'Survoltage et remplacement de batterie'),
  ('service.automotive.pre-purchase-inspection', 'fr', 'Inspection avant achat'),
  ('service.automotive.towing-and-roadside', 'fr', 'Remorquage et assistance routière'),
  ('service.automotive.ev-charger-install', 'fr', 'Installation de borne de recharge'),
  ('service.home-trades', 'fr', 'Métiers du bâtiment'),
  ('service.home-trades.plumber', 'fr', 'Plombier'),
  ('service.home-trades.electrician', 'fr', 'Électricien'),
  ('service.home-trades.gas-fitter', 'fr', 'Monteur d’installations au gaz'),
  ('service.home-trades.hvac-and-furnace', 'fr', 'CVC et fournaise'),
  ('service.home-trades.hot-water-tank', 'fr', 'Chauffe-eau'),
  ('service.home-trades.drywall-and-taping', 'fr', 'Cloisons sèches et joints'),
  ('service.home-trades.painting', 'fr', 'Peinture'),
  ('service.home-trades.flooring-and-tile', 'fr', 'Planchers et carrelage'),
  ('service.home-trades.carpentry-and-finishing', 'fr', 'Menuiserie et finition'),
  ('service.home-trades.roofing', 'fr', 'Toiture'),
  ('service.home-trades.eavestrough', 'fr', 'Gouttières'),
  ('service.home-trades.siding-and-exterior', 'fr', 'Revêtement et extérieur'),
  ('service.home-trades.fencing-and-decks', 'fr', 'Clôtures et terrasses'),
  ('service.home-trades.concrete-and-paving', 'fr', 'Béton et pavage'),
  ('service.home-trades.foundation-and-waterproofing', 'fr', 'Fondations et imperméabilisation'),
  ('service.home-trades.handyman', 'fr', 'Homme à tout faire'),
  ('service.home-trades.appliance-repair', 'fr', 'Réparation d’électroménagers'),
  ('service.home-trades.garage-doors', 'fr', 'Portes de garage'),
  ('service.home-trades.locksmith', 'fr', 'Serrurier'),
  ('service.home-trades.home-inspector', 'fr', 'Inspecteur en bâtiment'),
  ('service.cleaning-and-property', 'fr', 'Nettoyage et propriété'),
  ('service.cleaning-and-property.house-cleaning', 'fr', 'Ménage'),
  ('service.cleaning-and-property.move-in-move-out-clean', 'fr', 'Ménage d’emménagement / de déménagement'),
  ('service.cleaning-and-property.carpet-and-upholstery', 'fr', 'Tapis et meubles rembourrés'),
  ('service.cleaning-and-property.window-cleaning', 'fr', 'Lavage de vitres'),
  ('service.cleaning-and-property.pressure-washing', 'fr', 'Lavage à pression'),
  ('service.cleaning-and-property.junk-removal', 'fr', 'Enlèvement de rebuts'),
  ('service.cleaning-and-property.movers', 'fr', 'Déménageurs'),
  ('service.cleaning-and-property.snow-removal', 'fr', 'Déneigement'),
  ('service.cleaning-and-property.lawn-and-yard', 'fr', 'Pelouse et cour'),
  ('service.cleaning-and-property.landscaping', 'fr', 'Aménagement paysager'),
  ('service.cleaning-and-property.tree-service', 'fr', 'Élagage et abattage'),
  ('service.cleaning-and-property.pest-control', 'fr', 'Extermination'),
  ('service.cleaning-and-property.duct-cleaning', 'fr', 'Nettoyage de conduits'),
  ('service.cleaning-and-property.pool-and-hot-tub-service', 'fr', 'Entretien de piscine et spa'),
  ('service.cleaning-and-property.property-management', 'fr', 'Gestion immobilière'),
  ('service.events-and-hospitality', 'fr', 'Événements et accueil'),
  ('service.events-and-hospitality.cocktail-and-mocktail-bar', 'fr', 'Bar à cocktails'),
  ('service.events-and-hospitality.bartender', 'fr', 'Barman'),
  ('service.events-and-hospitality.event-planner', 'fr', 'Organisateur d’événements'),
  ('service.events-and-hospitality.wedding-planner', 'fr', 'Organisateur de mariage'),
  ('service.events-and-hospitality.dj', 'fr', 'DJ'),
  ('service.events-and-hospitality.live-music', 'fr', 'Musique live'),
  ('service.events-and-hospitality.photographer', 'fr', 'Photographe'),
  ('service.events-and-hospitality.videographer', 'fr', 'Vidéaste'),
  ('service.events-and-hospitality.photo-booth', 'fr', 'Photomaton'),
  ('service.events-and-hospitality.florist', 'fr', 'Fleuriste'),
  ('service.events-and-hospitality.balloon-and-decor', 'fr', 'Ballons et décor'),
  ('service.events-and-hospitality.rentals-tents-tables-chairs', 'fr', 'Location · tentes, tables, chaises'),
  ('service.events-and-hospitality.catering-server-staff', 'fr', 'Personnel de service traiteur'),
  ('service.events-and-hospitality.mc-host', 'fr', 'Animateur / maître de cérémonie'),
  ('service.events-and-hospitality.kids-party-entertainer', 'fr', 'Animateur de fêtes d’enfants'),
  ('service.personal-care-and-wellness', 'fr', 'Soins personnels et bien-être'),
  ('service.personal-care-and-wellness.barber-and-hair', 'fr', 'Coiffure'),
  ('service.personal-care-and-wellness.mobile-hair-and-makeup', 'fr', 'Coiffure et maquillage à domicile'),
  ('service.personal-care-and-wellness.nail-technician', 'fr', 'Technicienne en ongles'),
  ('service.personal-care-and-wellness.esthetician', 'fr', 'Esthéticienne'),
  ('service.personal-care-and-wellness.massage-therapist', 'fr', 'Massothérapeute'),
  ('service.personal-care-and-wellness.personal-trainer', 'fr', 'Entraîneur personnel'),
  ('service.personal-care-and-wellness.yoga-pilates-instructor', 'fr', 'Professeur de yoga / pilates'),
  ('service.personal-care-and-wellness.nutritionist', 'fr', 'Nutritionniste'),
  ('service.personal-care-and-wellness.registered-dietitian', 'fr', 'Diététiste'),
  ('service.personal-care-and-wellness.physiotherapist', 'fr', 'Physiothérapeute'),
  ('service.personal-care-and-wellness.doula', 'fr', 'Doula'),
  ('service.personal-care-and-wellness.home-care-aide', 'fr', 'Aide à domicile'),
  ('service.pets', 'fr', 'Animaux'),
  ('service.pets.dog-walker', 'fr', 'Promeneur de chiens'),
  ('service.pets.pet-sitter', 'fr', 'Gardien d’animaux'),
  ('service.pets.dog-grooming', 'fr', 'Toilettage de chiens'),
  ('service.pets.dog-training', 'fr', 'Dressage de chiens'),
  ('service.pets.pet-taxi', 'fr', 'Taxi pour animaux'),
  ('service.education-and-coaching', 'fr', 'Éducation et coaching'),
  ('service.education-and-coaching.tutor-k-12', 'fr', 'Tuteur · primaire et secondaire'),
  ('service.education-and-coaching.tutor-post-secondary', 'fr', 'Tuteur · postsecondaire'),
  ('service.education-and-coaching.music-lessons', 'fr', 'Cours de musique'),
  ('service.education-and-coaching.language-lessons', 'fr', 'Cours de langue'),
  ('service.education-and-coaching.driving-instructor', 'fr', 'Moniteur de conduite'),
  ('service.education-and-coaching.swim-instructor', 'fr', 'Moniteur de natation'),
  ('service.education-and-coaching.test-prep', 'fr', 'Préparation aux examens'),
  ('service.education-and-coaching.career-coach', 'fr', 'Coach de carrière'),
  ('service.education-and-coaching.life-coach', 'fr', 'Coach de vie'),
  ('service.professional', 'fr', 'Services professionnels'),
  ('service.professional.real-estate-agent', 'fr', 'Courtier immobilier'),
  ('service.professional.mortgage-broker', 'fr', 'Courtier hypothécaire'),
  ('service.professional.accountant-bookkeeper', 'fr', 'Comptable / teneur de livres'),
  ('service.professional.tax-preparer', 'fr', 'Préparateur de déclarations'),
  ('service.professional.notary', 'fr', 'Notaire'),
  ('service.professional.immigration-consultant', 'fr', 'Consultant en immigration'),
  ('service.professional.insurance-broker', 'fr', 'Courtier d’assurance'),
  ('service.professional.translator', 'fr', 'Traducteur'),
  ('service.professional.legal-document-services', 'fr', 'Services de documents juridiques'),
  ('service.tech-and-digital', 'fr', 'Technologie et numérique'),
  ('service.tech-and-digital.computer-repair', 'fr', 'Réparation d’ordinateurs'),
  ('service.tech-and-digital.phone-and-tablet-repair', 'fr', 'Réparation de téléphones et tablettes'),
  ('service.tech-and-digital.home-network-and-wi-fi', 'fr', 'Réseau domestique et Wi-Fi'),
  ('service.tech-and-digital.smart-home-install', 'fr', 'Installation domotique'),
  ('service.tech-and-digital.tv-mounting', 'fr', 'Installation de téléviseur'),
  ('service.tech-and-digital.web-design', 'fr', 'Conception Web'),
  ('service.tech-and-digital.photography-editing', 'fr', 'Retouche photo'),
  ('service.tech-and-digital.it-support-for-small-business', 'fr', 'Soutien informatique pour PME'),
  ('service.childcare-and-family', 'fr', 'Garde d’enfants et famille'),
  ('service.childcare-and-family.babysitter', 'fr', 'Gardienne'),
  ('service.childcare-and-family.nanny', 'fr', 'Nounou'),
  ('service.childcare-and-family.newborn-care', 'fr', 'Soins aux nouveau-nés'),
  ('service.childcare-and-family.senior-companionship', 'fr', 'Compagnie pour aînés'),
  ('service.childcare-and-family.errand-and-shopping-help', 'fr', 'Courses et commissions'),
  ('food.format', 'fr', 'Format'),
  ('food.format.restaurant-dine-in-and-takeout', 'fr', 'Restaurant · sur place et à emporter'),
  ('food.format.takeout-only', 'fr', 'Commandes à emporter seulement'),
  ('food.format.ghost-kitchen', 'fr', 'Cuisine virtuelle'),
  ('food.format.food-truck', 'fr', 'Camion-restaurant'),
  ('food.format.home-based-food-business', 'fr', 'Entreprise alimentaire à domicile'),
  ('food.format.grocery-with-hot-counter', 'fr', 'Épicerie avec comptoir de mets chauds'),
  ('food.service', 'fr', 'Service'),
  ('food.service.caterer', 'fr', 'Traiteur'),
  ('food.service.meal-prep-weekly-plans', 'fr', 'Repas préparés · formules hebdomadaires'),
  ('food.service.bakery', 'fr', 'Boulangerie'),
  ('food.service.coffee-and-dessert', 'fr', 'Café et desserts'),
  ('food.service.juice-and-smoothies', 'fr', 'Jus et smoothies'),
  ('food.service.alcohol-with-food', 'fr', 'Alcool servi avec les repas')
ON CONFLICT (category_id, lang) DO NOTHING;

-- Readers that take name_i18n ->> 'fr' (Studio pickers, onboarding, search, listings) see the same French; seedCategories
-- copies the labels into name_i18n from now on (CategorySeeder). Rows staff edited keep their own names.
UPDATE catalogue.categories c
   SET name_i18n = coalesce(c.name_i18n, '{}'::jsonb) || jsonb_build_object('fr', l.name)
  FROM catalogue.category_labels l
 WHERE l.category_id = c.id AND l.lang = 'fr' AND c.edited_at IS NULL
   AND coalesce(c.name_i18n ->> 'fr', '') = '';
