/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as BMerchantIdRouteImport } from './routes/b.$merchantId'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as OnboardingStepRouteImport } from './routes/onboarding/$step'
import { Route as BMerchantIdIndexRouteImport } from './routes/b.$merchantId/index'
import { Route as BMerchantIdAppointmentsRouteImport } from './routes/b.$merchantId/appointments'
import { Route as BMerchantIdAvailabilityRouteImport } from './routes/b.$merchantId/availability'
import { Route as BMerchantIdComplianceRouteImport } from './routes/b.$merchantId/compliance'
import { Route as BMerchantIdEarningsRouteImport } from './routes/b.$merchantId/earnings'
import { Route as BMerchantIdHelpRouteImport } from './routes/b.$merchantId/help'
import { Route as BMerchantIdMessagesRouteImport } from './routes/b.$merchantId/messages'
import { Route as BMerchantIdOrdersRouteImport } from './routes/b.$merchantId/orders'
import { Route as BMerchantIdPageRouteImport } from './routes/b.$merchantId/page'
import { Route as BMerchantIdPayoutsRouteImport } from './routes/b.$merchantId/payouts'
import { Route as BMerchantIdRefundsRouteImport } from './routes/b.$merchantId/refunds'
import { Route as BMerchantIdReportsRouteImport } from './routes/b.$merchantId/reports'
import { Route as BMerchantIdReviewsRouteImport } from './routes/b.$merchantId/reviews'
import { Route as BMerchantIdSettingsRouteImport } from './routes/b.$merchantId/settings'
import { Route as BMerchantIdKitchenCombosRouteImport } from './routes/b.$merchantId/kitchen/combos'
import { Route as BMerchantIdKitchenHoursRouteImport } from './routes/b.$merchantId/kitchen/hours'
import { Route as BMerchantIdKitchenLiveRouteImport } from './routes/b.$merchantId/kitchen/live'
import { Route as BMerchantIdKitchenMenuRouteImport } from './routes/b.$merchantId/kitchen/menu'
import { Route as BMerchantIdListingsIndexRouteImport } from './routes/b.$merchantId/listings/index'
import { Route as BMerchantIdListingsListingIdRouteImport } from './routes/b.$merchantId/listings/$listingId'
import { Route as BMerchantIdListingsBulkRouteImport } from './routes/b.$merchantId/listings/bulk'
import { Route as BMerchantIdListingsNewRouteImport } from './routes/b.$merchantId/listings/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const BMerchantIdRoute = BMerchantIdRouteImport.update({
  id: '/b/$merchantId',
  path: '/b/$merchantId',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStepRoute = OnboardingStepRouteImport.update({
  id: '/onboarding/$step',
  path: '/onboarding/$step',
  getParentRoute: () => rootRouteImport,
} as any)
const BMerchantIdIndexRoute = BMerchantIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BMerchantIdRoute,
} as any)
const BMerchantIdAppointmentsRoute = BMerchantIdAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => BMerchantIdRoute,
} as any)
const BMerchantIdAvailabilityRoute = BMerchantIdAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => BMerchantIdRoute,
} as any)
const BMerchantIdComplianceRoute = BMerchantIdComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => BMerchantIdRoute,
} as any)
const BMerchantIdEarningsRoute = BMerchantIdEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => BMerchantIdRoute,
} as any)
const BMerchantIdHelpRoute = BMerchantIdHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => BMerchantIdRoute,
} as any)
const BMerchantIdMessagesRoute = BMerchantIdMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => BMerchantIdRoute,
} as any)
const BMerchantIdOrdersRoute = BMerchantIdOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => BMerchantIdRoute,
} as any)
const BMerchantIdPageRoute = BMerchantIdPageRouteImport.update({
  id: '/page',
  path: '/page',
  getParentRoute: () => BMerchantIdRoute,
} as any)
const BMerchantIdPayoutsRoute = BMerchantIdPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => BMerchantIdRoute,
} as any)
const BMerchantIdRefundsRoute = BMerchantIdRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => BMerchantIdRoute,
} as any)
const BMerchantIdReportsRoute = BMerchantIdReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => BMerchantIdRoute,
} as any)
const BMerchantIdReviewsRoute = BMerchantIdReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => BMerchantIdRoute,
} as any)
const BMerchantIdSettingsRoute = BMerchantIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BMerchantIdRoute,
} as any)
const BMerchantIdKitchenCombosRoute =
  BMerchantIdKitchenCombosRouteImport.update({
    id: '/kitchen/combos',
    path: '/kitchen/combos',
    getParentRoute: () => BMerchantIdRoute,
  } as any)
const BMerchantIdKitchenHoursRoute = BMerchantIdKitchenHoursRouteImport.update({
  id: '/kitchen/hours',
  path: '/kitchen/hours',
  getParentRoute: () => BMerchantIdRoute,
} as any)
const BMerchantIdKitchenLiveRoute = BMerchantIdKitchenLiveRouteImport.update({
  id: '/kitchen/live',
  path: '/kitchen/live',
  getParentRoute: () => BMerchantIdRoute,
} as any)
const BMerchantIdKitchenMenuRoute = BMerchantIdKitchenMenuRouteImport.update({
  id: '/kitchen/menu',
  path: '/kitchen/menu',
  getParentRoute: () => BMerchantIdRoute,
} as any)
const BMerchantIdListingsIndexRoute =
  BMerchantIdListingsIndexRouteImport.update({
    id: '/listings/',
    path: '/listings/',
    getParentRoute: () => BMerchantIdRoute,
  } as any)
const BMerchantIdListingsListingIdRoute =
  BMerchantIdListingsListingIdRouteImport.update({
    id: '/listings/$listingId',
    path: '/listings/$listingId',
    getParentRoute: () => BMerchantIdRoute,
  } as any)
const BMerchantIdListingsBulkRoute = BMerchantIdListingsBulkRouteImport.update({
  id: '/listings/bulk',
  path: '/listings/bulk',
  getParentRoute: () => BMerchantIdRoute,
} as any)
const BMerchantIdListingsNewRoute = BMerchantIdListingsNewRouteImport.update({
  id: '/listings/new',
  path: '/listings/new',
  getParentRoute: () => BMerchantIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/sign-in': typeof SignInRoute
  '/b/$merchantId': typeof BMerchantIdRouteWithChildren
  '/onboarding/$step': typeof OnboardingStepRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/b/$merchantId/appointments': typeof BMerchantIdAppointmentsRoute
  '/b/$merchantId/availability': typeof BMerchantIdAvailabilityRoute
  '/b/$merchantId/compliance': typeof BMerchantIdComplianceRoute
  '/b/$merchantId/earnings': typeof BMerchantIdEarningsRoute
  '/b/$merchantId/help': typeof BMerchantIdHelpRoute
  '/b/$merchantId/messages': typeof BMerchantIdMessagesRoute
  '/b/$merchantId/orders': typeof BMerchantIdOrdersRoute
  '/b/$merchantId/page': typeof BMerchantIdPageRoute
  '/b/$merchantId/payouts': typeof BMerchantIdPayoutsRoute
  '/b/$merchantId/refunds': typeof BMerchantIdRefundsRoute
  '/b/$merchantId/reports': typeof BMerchantIdReportsRoute
  '/b/$merchantId/reviews': typeof BMerchantIdReviewsRoute
  '/b/$merchantId/settings': typeof BMerchantIdSettingsRoute
  '/b/$merchantId/': typeof BMerchantIdIndexRoute
  '/b/$merchantId/kitchen/combos': typeof BMerchantIdKitchenCombosRoute
  '/b/$merchantId/kitchen/hours': typeof BMerchantIdKitchenHoursRoute
  '/b/$merchantId/kitchen/live': typeof BMerchantIdKitchenLiveRoute
  '/b/$merchantId/kitchen/menu': typeof BMerchantIdKitchenMenuRoute
  '/b/$merchantId/listings/$listingId': typeof BMerchantIdListingsListingIdRoute
  '/b/$merchantId/listings/bulk': typeof BMerchantIdListingsBulkRoute
  '/b/$merchantId/listings/new': typeof BMerchantIdListingsNewRoute
  '/b/$merchantId/listings/': typeof BMerchantIdListingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/sign-in': typeof SignInRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/b/$merchantId/appointments': typeof BMerchantIdAppointmentsRoute
  '/b/$merchantId/availability': typeof BMerchantIdAvailabilityRoute
  '/b/$merchantId/compliance': typeof BMerchantIdComplianceRoute
  '/b/$merchantId/earnings': typeof BMerchantIdEarningsRoute
  '/b/$merchantId/help': typeof BMerchantIdHelpRoute
  '/b/$merchantId/messages': typeof BMerchantIdMessagesRoute
  '/b/$merchantId/orders': typeof BMerchantIdOrdersRoute
  '/b/$merchantId/page': typeof BMerchantIdPageRoute
  '/b/$merchantId/payouts': typeof BMerchantIdPayoutsRoute
  '/b/$merchantId/refunds': typeof BMerchantIdRefundsRoute
  '/b/$merchantId/reports': typeof BMerchantIdReportsRoute
  '/b/$merchantId/reviews': typeof BMerchantIdReviewsRoute
  '/b/$merchantId/settings': typeof BMerchantIdSettingsRoute
  '/b/$merchantId': typeof BMerchantIdIndexRoute
  '/b/$merchantId/kitchen/combos': typeof BMerchantIdKitchenCombosRoute
  '/b/$merchantId/kitchen/hours': typeof BMerchantIdKitchenHoursRoute
  '/b/$merchantId/kitchen/live': typeof BMerchantIdKitchenLiveRoute
  '/b/$merchantId/kitchen/menu': typeof BMerchantIdKitchenMenuRoute
  '/b/$merchantId/listings/$listingId': typeof BMerchantIdListingsListingIdRoute
  '/b/$merchantId/listings/bulk': typeof BMerchantIdListingsBulkRoute
  '/b/$merchantId/listings/new': typeof BMerchantIdListingsNewRoute
  '/b/$merchantId/listings': typeof BMerchantIdListingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/sign-in': typeof SignInRoute
  '/b/$merchantId': typeof BMerchantIdRouteWithChildren
  '/onboarding/$step': typeof OnboardingStepRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/b/$merchantId/appointments': typeof BMerchantIdAppointmentsRoute
  '/b/$merchantId/availability': typeof BMerchantIdAvailabilityRoute
  '/b/$merchantId/compliance': typeof BMerchantIdComplianceRoute
  '/b/$merchantId/earnings': typeof BMerchantIdEarningsRoute
  '/b/$merchantId/help': typeof BMerchantIdHelpRoute
  '/b/$merchantId/messages': typeof BMerchantIdMessagesRoute
  '/b/$merchantId/orders': typeof BMerchantIdOrdersRoute
  '/b/$merchantId/page': typeof BMerchantIdPageRoute
  '/b/$merchantId/payouts': typeof BMerchantIdPayoutsRoute
  '/b/$merchantId/refunds': typeof BMerchantIdRefundsRoute
  '/b/$merchantId/reports': typeof BMerchantIdReportsRoute
  '/b/$merchantId/reviews': typeof BMerchantIdReviewsRoute
  '/b/$merchantId/settings': typeof BMerchantIdSettingsRoute
  '/b/$merchantId/': typeof BMerchantIdIndexRoute
  '/b/$merchantId/kitchen/combos': typeof BMerchantIdKitchenCombosRoute
  '/b/$merchantId/kitchen/hours': typeof BMerchantIdKitchenHoursRoute
  '/b/$merchantId/kitchen/live': typeof BMerchantIdKitchenLiveRoute
  '/b/$merchantId/kitchen/menu': typeof BMerchantIdKitchenMenuRoute
  '/b/$merchantId/listings/$listingId': typeof BMerchantIdListingsListingIdRoute
  '/b/$merchantId/listings/bulk': typeof BMerchantIdListingsBulkRoute
  '/b/$merchantId/listings/new': typeof BMerchantIdListingsNewRoute
  '/b/$merchantId/listings/': typeof BMerchantIdListingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/sign-in'
    | '/b/$merchantId'
    | '/onboarding/$step'
    | '/onboarding/'
    | '/b/$merchantId/appointments'
    | '/b/$merchantId/availability'
    | '/b/$merchantId/compliance'
    | '/b/$merchantId/earnings'
    | '/b/$merchantId/help'
    | '/b/$merchantId/messages'
    | '/b/$merchantId/orders'
    | '/b/$merchantId/page'
    | '/b/$merchantId/payouts'
    | '/b/$merchantId/refunds'
    | '/b/$merchantId/reports'
    | '/b/$merchantId/reviews'
    | '/b/$merchantId/settings'
    | '/b/$merchantId/'
    | '/b/$merchantId/kitchen/combos'
    | '/b/$merchantId/kitchen/hours'
    | '/b/$merchantId/kitchen/live'
    | '/b/$merchantId/kitchen/menu'
    | '/b/$merchantId/listings/$listingId'
    | '/b/$merchantId/listings/bulk'
    | '/b/$merchantId/listings/new'
    | '/b/$merchantId/listings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/sign-in'
    | '/onboarding/$step'
    | '/onboarding'
    | '/b/$merchantId/appointments'
    | '/b/$merchantId/availability'
    | '/b/$merchantId/compliance'
    | '/b/$merchantId/earnings'
    | '/b/$merchantId/help'
    | '/b/$merchantId/messages'
    | '/b/$merchantId/orders'
    | '/b/$merchantId/page'
    | '/b/$merchantId/payouts'
    | '/b/$merchantId/refunds'
    | '/b/$merchantId/reports'
    | '/b/$merchantId/reviews'
    | '/b/$merchantId/settings'
    | '/b/$merchantId'
    | '/b/$merchantId/kitchen/combos'
    | '/b/$merchantId/kitchen/hours'
    | '/b/$merchantId/kitchen/live'
    | '/b/$merchantId/kitchen/menu'
    | '/b/$merchantId/listings/$listingId'
    | '/b/$merchantId/listings/bulk'
    | '/b/$merchantId/listings/new'
    | '/b/$merchantId/listings'
  id:
    | '__root__'
    | '/'
    | '/register'
    | '/sign-in'
    | '/b/$merchantId'
    | '/onboarding/$step'
    | '/onboarding/'
    | '/b/$merchantId/appointments'
    | '/b/$merchantId/availability'
    | '/b/$merchantId/compliance'
    | '/b/$merchantId/earnings'
    | '/b/$merchantId/help'
    | '/b/$merchantId/messages'
    | '/b/$merchantId/orders'
    | '/b/$merchantId/page'
    | '/b/$merchantId/payouts'
    | '/b/$merchantId/refunds'
    | '/b/$merchantId/reports'
    | '/b/$merchantId/reviews'
    | '/b/$merchantId/settings'
    | '/b/$merchantId/'
    | '/b/$merchantId/kitchen/combos'
    | '/b/$merchantId/kitchen/hours'
    | '/b/$merchantId/kitchen/live'
    | '/b/$merchantId/kitchen/menu'
    | '/b/$merchantId/listings/$listingId'
    | '/b/$merchantId/listings/bulk'
    | '/b/$merchantId/listings/new'
    | '/b/$merchantId/listings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegisterRoute: typeof RegisterRoute
  SignInRoute: typeof SignInRoute
  BMerchantIdRoute: typeof BMerchantIdRouteWithChildren
  OnboardingStepRoute: typeof OnboardingStepRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$merchantId': {
      id: '/b/$merchantId'
      path: '/b/$merchantId'
      fullPath: '/b/$merchantId'
      preLoaderRoute: typeof BMerchantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/$step': {
      id: '/onboarding/$step'
      path: '/onboarding/$step'
      fullPath: '/onboarding/$step'
      preLoaderRoute: typeof OnboardingStepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$merchantId/': {
      id: '/b/$merchantId/'
      path: '/'
      fullPath: '/b/$merchantId/'
      preLoaderRoute: typeof BMerchantIdIndexRouteImport
      parentRoute: typeof BMerchantIdRoute
    }
    '/b/$merchantId/appointments': {
      id: '/b/$merchantId/appointments'
      path: '/appointments'
      fullPath: '/b/$merchantId/appointments'
      preLoaderRoute: typeof BMerchantIdAppointmentsRouteImport
      parentRoute: typeof BMerchantIdRoute
    }
    '/b/$merchantId/availability': {
      id: '/b/$merchantId/availability'
      path: '/availability'
      fullPath: '/b/$merchantId/availability'
      preLoaderRoute: typeof BMerchantIdAvailabilityRouteImport
      parentRoute: typeof BMerchantIdRoute
    }
    '/b/$merchantId/compliance': {
      id: '/b/$merchantId/compliance'
      path: '/compliance'
      fullPath: '/b/$merchantId/compliance'
      preLoaderRoute: typeof BMerchantIdComplianceRouteImport
      parentRoute: typeof BMerchantIdRoute
    }
    '/b/$merchantId/earnings': {
      id: '/b/$merchantId/earnings'
      path: '/earnings'
      fullPath: '/b/$merchantId/earnings'
      preLoaderRoute: typeof BMerchantIdEarningsRouteImport
      parentRoute: typeof BMerchantIdRoute
    }
    '/b/$merchantId/help': {
      id: '/b/$merchantId/help'
      path: '/help'
      fullPath: '/b/$merchantId/help'
      preLoaderRoute: typeof BMerchantIdHelpRouteImport
      parentRoute: typeof BMerchantIdRoute
    }
    '/b/$merchantId/messages': {
      id: '/b/$merchantId/messages'
      path: '/messages'
      fullPath: '/b/$merchantId/messages'
      preLoaderRoute: typeof BMerchantIdMessagesRouteImport
      parentRoute: typeof BMerchantIdRoute
    }
    '/b/$merchantId/orders': {
      id: '/b/$merchantId/orders'
      path: '/orders'
      fullPath: '/b/$merchantId/orders'
      preLoaderRoute: typeof BMerchantIdOrdersRouteImport
      parentRoute: typeof BMerchantIdRoute
    }
    '/b/$merchantId/page': {
      id: '/b/$merchantId/page'
      path: '/page'
      fullPath: '/b/$merchantId/page'
      preLoaderRoute: typeof BMerchantIdPageRouteImport
      parentRoute: typeof BMerchantIdRoute
    }
    '/b/$merchantId/payouts': {
      id: '/b/$merchantId/payouts'
      path: '/payouts'
      fullPath: '/b/$merchantId/payouts'
      preLoaderRoute: typeof BMerchantIdPayoutsRouteImport
      parentRoute: typeof BMerchantIdRoute
    }
    '/b/$merchantId/refunds': {
      id: '/b/$merchantId/refunds'
      path: '/refunds'
      fullPath: '/b/$merchantId/refunds'
      preLoaderRoute: typeof BMerchantIdRefundsRouteImport
      parentRoute: typeof BMerchantIdRoute
    }
    '/b/$merchantId/reports': {
      id: '/b/$merchantId/reports'
      path: '/reports'
      fullPath: '/b/$merchantId/reports'
      preLoaderRoute: typeof BMerchantIdReportsRouteImport
      parentRoute: typeof BMerchantIdRoute
    }
    '/b/$merchantId/reviews': {
      id: '/b/$merchantId/reviews'
      path: '/reviews'
      fullPath: '/b/$merchantId/reviews'
      preLoaderRoute: typeof BMerchantIdReviewsRouteImport
      parentRoute: typeof BMerchantIdRoute
    }
    '/b/$merchantId/settings': {
      id: '/b/$merchantId/settings'
      path: '/settings'
      fullPath: '/b/$merchantId/settings'
      preLoaderRoute: typeof BMerchantIdSettingsRouteImport
      parentRoute: typeof BMerchantIdRoute
    }
    '/b/$merchantId/kitchen/combos': {
      id: '/b/$merchantId/kitchen/combos'
      path: '/kitchen/combos'
      fullPath: '/b/$merchantId/kitchen/combos'
      preLoaderRoute: typeof BMerchantIdKitchenCombosRouteImport
      parentRoute: typeof BMerchantIdRoute
    }
    '/b/$merchantId/kitchen/hours': {
      id: '/b/$merchantId/kitchen/hours'
      path: '/kitchen/hours'
      fullPath: '/b/$merchantId/kitchen/hours'
      preLoaderRoute: typeof BMerchantIdKitchenHoursRouteImport
      parentRoute: typeof BMerchantIdRoute
    }
    '/b/$merchantId/kitchen/live': {
      id: '/b/$merchantId/kitchen/live'
      path: '/kitchen/live'
      fullPath: '/b/$merchantId/kitchen/live'
      preLoaderRoute: typeof BMerchantIdKitchenLiveRouteImport
      parentRoute: typeof BMerchantIdRoute
    }
    '/b/$merchantId/kitchen/menu': {
      id: '/b/$merchantId/kitchen/menu'
      path: '/kitchen/menu'
      fullPath: '/b/$merchantId/kitchen/menu'
      preLoaderRoute: typeof BMerchantIdKitchenMenuRouteImport
      parentRoute: typeof BMerchantIdRoute
    }
    '/b/$merchantId/listings/': {
      id: '/b/$merchantId/listings/'
      path: '/listings'
      fullPath: '/b/$merchantId/listings/'
      preLoaderRoute: typeof BMerchantIdListingsIndexRouteImport
      parentRoute: typeof BMerchantIdRoute
    }
    '/b/$merchantId/listings/$listingId': {
      id: '/b/$merchantId/listings/$listingId'
      path: '/listings/$listingId'
      fullPath: '/b/$merchantId/listings/$listingId'
      preLoaderRoute: typeof BMerchantIdListingsListingIdRouteImport
      parentRoute: typeof BMerchantIdRoute
    }
    '/b/$merchantId/listings/bulk': {
      id: '/b/$merchantId/listings/bulk'
      path: '/listings/bulk'
      fullPath: '/b/$merchantId/listings/bulk'
      preLoaderRoute: typeof BMerchantIdListingsBulkRouteImport
      parentRoute: typeof BMerchantIdRoute
    }
    '/b/$merchantId/listings/new': {
      id: '/b/$merchantId/listings/new'
      path: '/listings/new'
      fullPath: '/b/$merchantId/listings/new'
      preLoaderRoute: typeof BMerchantIdListingsNewRouteImport
      parentRoute: typeof BMerchantIdRoute
    }
  }
}

interface BMerchantIdRouteChildren {
  BMerchantIdAppointmentsRoute: typeof BMerchantIdAppointmentsRoute
  BMerchantIdAvailabilityRoute: typeof BMerchantIdAvailabilityRoute
  BMerchantIdComplianceRoute: typeof BMerchantIdComplianceRoute
  BMerchantIdEarningsRoute: typeof BMerchantIdEarningsRoute
  BMerchantIdHelpRoute: typeof BMerchantIdHelpRoute
  BMerchantIdMessagesRoute: typeof BMerchantIdMessagesRoute
  BMerchantIdOrdersRoute: typeof BMerchantIdOrdersRoute
  BMerchantIdPageRoute: typeof BMerchantIdPageRoute
  BMerchantIdPayoutsRoute: typeof BMerchantIdPayoutsRoute
  BMerchantIdRefundsRoute: typeof BMerchantIdRefundsRoute
  BMerchantIdReportsRoute: typeof BMerchantIdReportsRoute
  BMerchantIdReviewsRoute: typeof BMerchantIdReviewsRoute
  BMerchantIdSettingsRoute: typeof BMerchantIdSettingsRoute
  BMerchantIdIndexRoute: typeof BMerchantIdIndexRoute
  BMerchantIdKitchenCombosRoute: typeof BMerchantIdKitchenCombosRoute
  BMerchantIdKitchenHoursRoute: typeof BMerchantIdKitchenHoursRoute
  BMerchantIdKitchenLiveRoute: typeof BMerchantIdKitchenLiveRoute
  BMerchantIdKitchenMenuRoute: typeof BMerchantIdKitchenMenuRoute
  BMerchantIdListingsListingIdRoute: typeof BMerchantIdListingsListingIdRoute
  BMerchantIdListingsBulkRoute: typeof BMerchantIdListingsBulkRoute
  BMerchantIdListingsNewRoute: typeof BMerchantIdListingsNewRoute
  BMerchantIdListingsIndexRoute: typeof BMerchantIdListingsIndexRoute
}

const BMerchantIdRouteChildren: BMerchantIdRouteChildren = {
  BMerchantIdAppointmentsRoute: BMerchantIdAppointmentsRoute,
  BMerchantIdAvailabilityRoute: BMerchantIdAvailabilityRoute,
  BMerchantIdComplianceRoute: BMerchantIdComplianceRoute,
  BMerchantIdEarningsRoute: BMerchantIdEarningsRoute,
  BMerchantIdHelpRoute: BMerchantIdHelpRoute,
  BMerchantIdMessagesRoute: BMerchantIdMessagesRoute,
  BMerchantIdOrdersRoute: BMerchantIdOrdersRoute,
  BMerchantIdPageRoute: BMerchantIdPageRoute,
  BMerchantIdPayoutsRoute: BMerchantIdPayoutsRoute,
  BMerchantIdRefundsRoute: BMerchantIdRefundsRoute,
  BMerchantIdReportsRoute: BMerchantIdReportsRoute,
  BMerchantIdReviewsRoute: BMerchantIdReviewsRoute,
  BMerchantIdSettingsRoute: BMerchantIdSettingsRoute,
  BMerchantIdIndexRoute: BMerchantIdIndexRoute,
  BMerchantIdKitchenCombosRoute: BMerchantIdKitchenCombosRoute,
  BMerchantIdKitchenHoursRoute: BMerchantIdKitchenHoursRoute,
  BMerchantIdKitchenLiveRoute: BMerchantIdKitchenLiveRoute,
  BMerchantIdKitchenMenuRoute: BMerchantIdKitchenMenuRoute,
  BMerchantIdListingsListingIdRoute: BMerchantIdListingsListingIdRoute,
  BMerchantIdListingsBulkRoute: BMerchantIdListingsBulkRoute,
  BMerchantIdListingsNewRoute: BMerchantIdListingsNewRoute,
  BMerchantIdListingsIndexRoute: BMerchantIdListingsIndexRoute,
}

const BMerchantIdRouteWithChildren = BMerchantIdRoute._addFileChildren(
  BMerchantIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegisterRoute: RegisterRoute,
  SignInRoute: SignInRoute,
  BMerchantIdRoute: BMerchantIdRouteWithChildren,
  OnboardingStepRoute: OnboardingStepRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
