import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/** The repository's docs/ (internal variant). Runbooks, security and AI follow their folders. */
const sidebars: SidebarsConfig = {
  repo: [
    {
      type: 'category',
      label: 'Overview',
      collapsed: false,
      items: ['ARCHITECTURE', 'DATA_MODEL', 'SCREENS', 'LOCAL_DEVELOPMENT'],
    },
    {
      type: 'category',
      label: 'Plans and conventions',
      items: ['IMPLEMENTATION_PLAN', 'CONSUMER_WEB_PLAN', 'BACKEND_CONVENTIONS', 'backlog/README'],
    },
    {
      type: 'category',
      label: 'Runbooks',
      link: { type: 'doc', id: 'runbooks/README' },
      items: [{ type: 'autogenerated', dirName: 'runbooks' }],
    },
    'DECISIONS',
    { type: 'category', label: 'Security', items: [{ type: 'autogenerated', dirName: 'security' }] },
    // S-109: the WCAG 2.2 AA audit and the accessibility statement.
    { type: 'category', label: 'Accessibility', items: [{ type: 'autogenerated', dirName: 'a11y' }] },
    // The in-product AI features (Spring AI with OpenRouter) are documented in docs/ai by their own story.
    { type: 'category', label: 'AI', items: [{ type: 'autogenerated', dirName: 'ai' }] },
  ],
};

export default sidebars;
