import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/** The repository's docs/ (internal variant). Runbooks, security and AI follow their folders. */
const sidebars: SidebarsConfig = {
  repo: [
    {
      type: 'category',
      label: 'Overview',
      collapsed: false,
      items: ['ARCHITECTURE', 'DATA_MODEL', 'SCREENS', 'LOCAL_DEVELOPMENT'],
    },
    {
      type: 'category',
      label: 'Plans and conventions',
      items: ['IMPLEMENTATION_PLAN', 'CONSUMER_WEB_PLAN', 'BACKEND_CONVENTIONS', 'backlog/README'],
    },
    {
      type: 'category',
      label: 'Runbooks',
      link: { type: 'doc', id: 'runbooks/README' },
      items: [{ type: 'autogenerated', dirName: 'runbooks' }],
    },
    'DECISIONS',
    { type: 'category', label: 'Security', items: [{ type: 'autogenerated', dirName: 'security' }] },
    // S-110 / S-106: the PCI DSS SAQ A packet and the legal counsel review packet.
    {
      type: 'category',
      label: 'Compliance',
      link: { type: 'doc', id: 'compliance/README' },
      items: [{ type: 'autogenerated', dirName: 'compliance' }],
    },
    // S-109: the WCAG 2.2 AA audit and the accessibility statement.
    { type: 'category', label: 'Accessibility', items: [{ type: 'autogenerated', dirName: 'a11y' }] },
    // S-119: load and soak test results and the launch capacity plan.
    { type: 'category', label: 'Performance', items: [{ type: 'autogenerated', dirName: 'perf' }] },
    // S-121: UAT with the pilot group — the process, the scripts and sign-off forms per persona (en/fr), the dry run.
    {
      type: 'category',
      label: 'UAT',
      link: { type: 'doc', id: 'uat/README' },
      items: [{ type: 'autogenerated', dirName: 'uat' }],
    },
    // The in-product AI features (Spring AI with OpenRouter) are documented in docs/ai by their own story.
    { type: 'category', label: 'AI', items: [{ type: 'autogenerated', dirName: 'ai' }] },
  ],
};

export default sidebars;
