import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import type { ConfigContext, ExpoConfig } from 'expo/config';

/**
 * Northline Courier (S-87): the single source of both native projects (Continuous Native Generation: android/ and
 * ios/ are generated by `expo prebuild` / EAS Build and never committed). docs/runbooks/courier-app.md.
 *
 * Build-time environment (EAS profiles in eas.json, or your shell):
 *   APP_VARIANT              development | preview | production (bundle id, name)
 *   EXPO_PUBLIC_API_URL      https://api.<zone>/api/v1
 *   EXPO_PUBLIC_AUTH_ISSUER  https://auth.<zone>
 *   EXPO_PUBLIC_FIXTURES     1 = the in-app fixture backend (web smoke test, demos); refused for production
 *   EAS_PROJECT_ID, EAS_OWNER  the Expo project (from `eas init`)
 *   GOOGLE_SERVICES_JSON     path of the environment's google-services.json (FCM); an EAS file variable, never committed
 */
type Env = Record<string, string | undefined>;

export type Variant = 'development' | 'preview' | 'production';
export const VARIANTS: Readonly<Record<Variant, { id: string; name: string }>> = {
  development: { id: 'ca.northline.courier.dev', name: 'Courier (Dev)' },
  preview: { id: 'ca.northline.courier.preview', name: 'Courier (Preview)' },
  production: { id: 'ca.northline.courier', name: 'Northline Courier' },
};

/**
 * The redirect registered for the `courier-app` client (server/auth application.yml): every variant uses it, since
 * northline-auth matches redirect URIs exactly. ASWebAuthenticationSession hands the redirect to the app that opened
 * it; on Android keep one variant installed at a time, or register a variant's own scheme (runbook § Variants).
 */
export const SCHEME = 'ca.northline.courier';
export const REDIRECT_URI = `${SCHEME}:/oauth2redirect`;
export const CLIENT_ID = 'courier-app';

/**
 * The marketing version (CFBundleShortVersionString / versionName): package.json's `version` is its one source
 * (`make mobile-version-set`); build numbers are EAS's (`appVersionSource: remote`). docs/runbooks/mobile-release.md.
 */
export const APP_VERSION: string = (JSON.parse(readFileSync(join(__dirname, 'package.json'), 'utf8')) as { version: string }).version;

/** Permission texts (en; fr-CA in locales/fr.json). Store reviewers read them: keep them exact and honest. */
export const PERMISSION_TEXT = {
  camera: 'Northline Courier uses the camera to photograph a delivery at the door as proof of delivery.',
  locationWhenInUse:
    'While you are on a run, Northline Courier shares your location so customers can follow their order on its way. Only your latest position is kept, never a history.',
  locationAlways:
    'While you are on a run, Northline Courier keeps sharing your location when the app is in the background, so customers can follow their order on its way. Sharing stops when your run ends; only your latest position is kept.',
  // mobile gaps part 1: a pilot courier's screenshot on feedback, from the system photo picker (expo-image-picker)
  photos: 'Northline Courier opens your photos only when you choose a screenshot to add to pilot feedback.',
} as const;

/**
 * Android permissions the app asks for; what libraries would add and the app does not use is removed from the merged
 * manifest. Background location: the run's foreground service (a visible notification) while a run is open.
 */
export const ANDROID_PERMISSIONS = [
  'android.permission.CAMERA',
  'android.permission.INTERNET',
  'android.permission.ACCESS_COARSE_LOCATION',
  'android.permission.ACCESS_FINE_LOCATION',
  'android.permission.ACCESS_BACKGROUND_LOCATION',
  'android.permission.FOREGROUND_SERVICE',
  'android.permission.FOREGROUND_SERVICE_LOCATION',
  // push (S-102/S-103): "New run", "Run changed"; Android 13+ asks
  'android.permission.POST_NOTIFICATIONS',
] as const;
export const ANDROID_BLOCKED_PERMISSIONS = [
  'android.permission.RECORD_AUDIO',
  'android.permission.SYSTEM_ALERT_WINDOW',
  'android.permission.READ_EXTERNAL_STORAGE',
  'android.permission.WRITE_EXTERNAL_STORAGE',
  'android.permission.READ_MEDIA_IMAGES',
  'android.permission.READ_MEDIA_VIDEO',
  'android.permission.READ_MEDIA_AUDIO',
] as const;

/** RN 0.86 / Expo SDK 57 toolchain levels. */
export const NATIVE = {
  android: { compileSdkVersion: 36, targetSdkVersion: 36, minSdkVersion: 24, buildToolsVersion: '36.0.0' },
  ios: { deploymentTarget: '16.4' },
} as const;

/** Brand colours for the native splash and icon background: the base tokens, read from @northline/tokens. */
function baseTokens(): { accent: string; bg: string } {
  const json = JSON.parse(readFileSync(join(__dirname, '../../../web/packages/tokens/tokens.json'), 'utf8')) as {
    base: { accent: string; bg: string };
  };
  return json.base;
}

export function resolveVariant(env: Env): Variant {
  return (['development', 'preview', 'production'] as const).find((v) => v === env.APP_VARIANT) ?? 'development';
}

export function createConfig(env: Env = process.env): ExpoConfig {
  const variant = resolveVariant(env);
  const v = VARIANTS[variant];
  const isDev = variant === 'development';
  const fixtures = env.EXPO_PUBLIC_FIXTURES === '1';
  if (variant === 'production' && fixtures) throw new Error('EXPO_PUBLIC_FIXTURES must not be set for a production build');
  const apiUrl = env.EXPO_PUBLIC_API_URL ?? 'http://localhost:8080/api/v1';
  const authIssuer = env.EXPO_PUBLIC_AUTH_ISSUER ?? 'http://localhost:9000';
  if (variant !== 'development' && !fixtures && (!apiUrl.startsWith('https://') || !authIssuer.startsWith('https://'))) {
    throw new Error('Preview and production builds need https EXPO_PUBLIC_API_URL and EXPO_PUBLIC_AUTH_ISSUER');
  }
  const easProjectId = env.EAS_PROJECT_ID ?? '00000000-0000-0000-0000-000000000000';
  const brand = baseTokens();

  return {
    name: v.name,
    slug: 'northline-courier',
    scheme: SCHEME,
    version: APP_VERSION,
    runtimeVersion: { policy: 'fingerprint' },
    updates: { url: `https://u.expo.dev/${easProjectId}`, fallbackToCacheTimeout: 0, checkAutomatically: 'ON_LOAD' },
    orientation: 'portrait',
    userInterfaceStyle: 'light',
    backgroundColor: brand.bg,
    icon: './assets/icon.png',
    // The permission texts in French (InfoPlist.strings); Android shows its own system texts.
    locales: { fr: './locales/fr.json' },
    ios: {
      bundleIdentifier: v.id,
      buildNumber: env.NL_IOS_BUILD_NUMBER || undefined,
      supportsTablet: false,
      config: { usesNonExemptEncryption: false },
      infoPlist: {
        CFBundleAllowMixedLocalizations: true,
        CFBundleLocalizations: ['en', 'fr'],
        NSCameraUsageDescription: PERMISSION_TEXT.camera,
        NSLocationWhenInUseUsageDescription: PERMISSION_TEXT.locationWhenInUse,
        NSLocationAlwaysAndWhenInUseUsageDescription: PERMISSION_TEXT.locationAlways,
        NSAppTransportSecurity: { NSAllowsArbitraryLoads: false, NSAllowsLocalNetworking: isDev },
      },
      privacyManifests: {
        NSPrivacyTracking: false,
        NSPrivacyTrackingDomains: [],
        NSPrivacyAccessedAPITypes: [
          { NSPrivacyAccessedAPIType: 'NSPrivacyAccessedAPICategoryUserDefaults', NSPrivacyAccessedAPITypeReasons: ['CA92.1'] },
          { NSPrivacyAccessedAPIType: 'NSPrivacyAccessedAPICategoryFileTimestamp', NSPrivacyAccessedAPITypeReasons: ['C617.1'] },
          { NSPrivacyAccessedAPIType: 'NSPrivacyAccessedAPICategorySystemBootTime', NSPrivacyAccessedAPITypeReasons: ['35F9.1'] },
          { NSPrivacyAccessedAPIType: 'NSPrivacyAccessedAPICategoryDiskSpace', NSPrivacyAccessedAPITypeReasons: ['E174.1'] },
        ],
        // Linked to the courier, for app functionality only: precise location while on a run, proof photos, the
        // push token (device id), the customer's signature at the door. Kept equal to store/privacy.json (S-103).
        NSPrivacyCollectedDataTypes: [
          'NSPrivacyCollectedDataTypePreciseLocation',
          'NSPrivacyCollectedDataTypePhotosorVideos',
          'NSPrivacyCollectedDataTypeUserID',
          'NSPrivacyCollectedDataTypeDeviceID',
          'NSPrivacyCollectedDataTypeOtherUserContent',
        ].map((type) => ({
          NSPrivacyCollectedDataType: type,
          NSPrivacyCollectedDataTypeLinked: true,
          NSPrivacyCollectedDataTypeTracking: false,
          NSPrivacyCollectedDataTypePurposes: ['NSPrivacyCollectedDataTypePurposeAppFunctionality'],
        })),
      },
    },
    android: {
      package: v.id,
      versionCode: env.NL_ANDROID_VERSION_CODE ? Number(env.NL_ANDROID_VERSION_CODE) : undefined,
      adaptiveIcon: { foregroundImage: './assets/adaptive-icon.png', backgroundColor: brand.accent },
      // The OAuth redirect: Custom Tabs hand the code back through this filter.
      intentFilters: [
        { action: 'VIEW', category: ['BROWSABLE', 'DEFAULT'], data: [{ scheme: SCHEME, path: '/oauth2redirect' }] },
      ],
      permissions: [...ANDROID_PERMISSIONS],
      blockedPermissions: [...ANDROID_BLOCKED_PERMISSIONS],
      allowBackup: false,
      // FCM (push): the environment's Firebase file, given to EAS Build as a file variable (docs/runbooks/push.md).
      googleServicesFile: env.GOOGLE_SERVICES_JSON || undefined,
    },
    web: { bundler: 'metro', output: 'single' },
    plugins: [
      'expo-router',
      ['expo-secure-store', { configureAndroidBackup: false }],
      'expo-font',
      'expo-localization',
      'expo-web-browser',
      ['expo-camera', { cameraPermission: PERMISSION_TEXT.camera, microphonePermission: false, recordAudioAndroid: false }],
      // mobile gaps part 1: the system photo picker for a pilot's screenshot — no library or storage permission; the
      // camera text stays expo-camera's (the picker's camera isn't used), no microphone
      ['expo-image-picker', { photosPermission: PERMISSION_TEXT.photos, cameraPermission: PERMISSION_TEXT.camera, microphonePermission: false }],
      [
        'expo-location',
        {
          locationWhenInUsePermission: PERMISSION_TEXT.locationWhenInUse,
          locationAlwaysAndWhenInUsePermission: PERMISSION_TEXT.locationAlways,
          isIosBackgroundLocationEnabled: true,
          isAndroidBackgroundLocationEnabled: true,
          isAndroidForegroundServiceEnabled: true,
        },
      ],
      // Push (S-102's registration in @northline/mobile-kit): the native module, the aps-environment entitlement
      // (production APNs for store builds) and the Android channel `updates` the worker sends to.
      ['expo-notifications', { mode: isDev ? 'development' : 'production', defaultChannel: 'updates', color: brand.accent, enableBackgroundRemoteNotifications: false }],
      ['expo-splash-screen', { image: './assets/splash-icon.png', imageWidth: 160, resizeMode: 'contain', backgroundColor: brand.bg }],
      [
        'expo-build-properties',
        {
          android: { ...NATIVE.android, enableMinifyInReleaseBuilds: true, enableShrinkResourcesInReleaseBuilds: true, usesCleartextTraffic: isDev },
          ios: { deploymentTarget: NATIVE.ios.deploymentTarget, privacyManifestAggregationEnabled: true },
        },
      ],
    ],
    // tsconfig "paths" only pin React's types; Metro resolves the runtime copies itself (metro.config.js)
    experiments: { typedRoutes: false, tsconfigPaths: false },
    owner: env.EAS_OWNER ?? 'northline',
    extra: { apiUrl, authIssuer, fixtures, variant, clientId: CLIENT_ID, redirectUri: REDIRECT_URI, eas: { projectId: easProjectId } },
  };
}

export default (_ctx: ConfigContext): ExpoConfig => createConfig(process.env);
