/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConsoleRouteImport } from './routes/_console'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ConsoleIndexRouteImport } from './routes/_console/index'
import { Route as ConsoleCatalogueRouteImport } from './routes/_console/catalogue'
import { Route as ConsoleDeliveryRouteImport } from './routes/_console/delivery'
import { Route as ConsoleDisputesRouteImport } from './routes/_console/disputes'
import { Route as ConsoleFinanceRouteImport } from './routes/_console/finance'
import { Route as ConsoleIntegrationsRouteImport } from './routes/_console/integrations'
import { Route as ConsoleOnCallRouteImport } from './routes/_console/on-call'
import { Route as ConsoleOrdersRouteImport } from './routes/_console/orders'
import { Route as ConsolePilotRouteImport } from './routes/_console/pilot'
import { Route as ConsolePrivacyRouteImport } from './routes/_console/privacy'
import { Route as ConsoleProfileRouteImport } from './routes/_console/profile'
import { Route as ConsoleProvincesRouteImport } from './routes/_console/provinces'
import { Route as ConsoleReportsRouteImport } from './routes/_console/reports'
import { Route as ConsoleSupportRouteImport } from './routes/_console/support'
import { Route as ConsoleTeamRouteImport } from './routes/_console/team'
import { Route as ConsoleTrustRouteImport } from './routes/_console/trust'
import { Route as ConsoleVerificationRouteImport } from './routes/_console/verification'
import { Route as ConsoleVettingRouteImport } from './routes/_console/vetting'
import { Route as ConsoleSellersIndexRouteImport } from './routes/_console/sellers.index'
import { Route as ConsoleSellersSellerIdRouteImport } from './routes/_console/sellers.$sellerId'

const ConsoleRoute = ConsoleRouteImport.update({
  id: '/_console',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleCatalogueRoute = ConsoleCatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleDeliveryRoute = ConsoleDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleDisputesRoute = ConsoleDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleFinanceRoute = ConsoleFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleIntegrationsRoute = ConsoleIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleOnCallRoute = ConsoleOnCallRouteImport.update({
  id: '/on-call',
  path: '/on-call',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleOrdersRoute = ConsoleOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsolePilotRoute = ConsolePilotRouteImport.update({
  id: '/pilot',
  path: '/pilot',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsolePrivacyRoute = ConsolePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleProfileRoute = ConsoleProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleProvincesRoute = ConsoleProvincesRouteImport.update({
  id: '/provinces',
  path: '/provinces',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleReportsRoute = ConsoleReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSupportRoute = ConsoleSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleTeamRoute = ConsoleTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleTrustRoute = ConsoleTrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleVerificationRoute = ConsoleVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleVettingRoute = ConsoleVettingRouteImport.update({
  id: '/vetting',
  path: '/vetting',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSellersIndexRoute = ConsoleSellersIndexRouteImport.update({
  id: '/sellers/',
  path: '/sellers/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSellersSellerIdRoute = ConsoleSellersSellerIdRouteImport.update({
  id: '/sellers/$sellerId',
  path: '/sellers/$sellerId',
  getParentRoute: () => ConsoleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ConsoleIndexRoute
  '/sign-in': typeof SignInRoute
  '/catalogue': typeof ConsoleCatalogueRoute
  '/delivery': typeof ConsoleDeliveryRoute
  '/disputes': typeof ConsoleDisputesRoute
  '/finance': typeof ConsoleFinanceRoute
  '/integrations': typeof ConsoleIntegrationsRoute
  '/on-call': typeof ConsoleOnCallRoute
  '/orders': typeof ConsoleOrdersRoute
  '/pilot': typeof ConsolePilotRoute
  '/privacy': typeof ConsolePrivacyRoute
  '/profile': typeof ConsoleProfileRoute
  '/provinces': typeof ConsoleProvincesRoute
  '/reports': typeof ConsoleReportsRoute
  '/support': typeof ConsoleSupportRoute
  '/team': typeof ConsoleTeamRoute
  '/trust': typeof ConsoleTrustRoute
  '/verification': typeof ConsoleVerificationRoute
  '/vetting': typeof ConsoleVettingRoute
  '/sellers/$sellerId': typeof ConsoleSellersSellerIdRoute
  '/sellers/': typeof ConsoleSellersIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/catalogue': typeof ConsoleCatalogueRoute
  '/delivery': typeof ConsoleDeliveryRoute
  '/disputes': typeof ConsoleDisputesRoute
  '/finance': typeof ConsoleFinanceRoute
  '/integrations': typeof ConsoleIntegrationsRoute
  '/on-call': typeof ConsoleOnCallRoute
  '/orders': typeof ConsoleOrdersRoute
  '/pilot': typeof ConsolePilotRoute
  '/privacy': typeof ConsolePrivacyRoute
  '/profile': typeof ConsoleProfileRoute
  '/provinces': typeof ConsoleProvincesRoute
  '/reports': typeof ConsoleReportsRoute
  '/support': typeof ConsoleSupportRoute
  '/team': typeof ConsoleTeamRoute
  '/trust': typeof ConsoleTrustRoute
  '/verification': typeof ConsoleVerificationRoute
  '/vetting': typeof ConsoleVettingRoute
  '/': typeof ConsoleIndexRoute
  '/sellers/$sellerId': typeof ConsoleSellersSellerIdRoute
  '/sellers': typeof ConsoleSellersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_console': typeof ConsoleRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_console/catalogue': typeof ConsoleCatalogueRoute
  '/_console/delivery': typeof ConsoleDeliveryRoute
  '/_console/disputes': typeof ConsoleDisputesRoute
  '/_console/finance': typeof ConsoleFinanceRoute
  '/_console/integrations': typeof ConsoleIntegrationsRoute
  '/_console/on-call': typeof ConsoleOnCallRoute
  '/_console/orders': typeof ConsoleOrdersRoute
  '/_console/pilot': typeof ConsolePilotRoute
  '/_console/privacy': typeof ConsolePrivacyRoute
  '/_console/profile': typeof ConsoleProfileRoute
  '/_console/provinces': typeof ConsoleProvincesRoute
  '/_console/reports': typeof ConsoleReportsRoute
  '/_console/support': typeof ConsoleSupportRoute
  '/_console/team': typeof ConsoleTeamRoute
  '/_console/trust': typeof ConsoleTrustRoute
  '/_console/verification': typeof ConsoleVerificationRoute
  '/_console/vetting': typeof ConsoleVettingRoute
  '/_console/': typeof ConsoleIndexRoute
  '/_console/sellers/$sellerId': typeof ConsoleSellersSellerIdRoute
  '/_console/sellers/': typeof ConsoleSellersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/catalogue'
    | '/delivery'
    | '/disputes'
    | '/finance'
    | '/integrations'
    | '/on-call'
    | '/orders'
    | '/pilot'
    | '/privacy'
    | '/profile'
    | '/provinces'
    | '/reports'
    | '/support'
    | '/team'
    | '/trust'
    | '/verification'
    | '/vetting'
    | '/sellers/$sellerId'
    | '/sellers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/catalogue'
    | '/delivery'
    | '/disputes'
    | '/finance'
    | '/integrations'
    | '/on-call'
    | '/orders'
    | '/pilot'
    | '/privacy'
    | '/profile'
    | '/provinces'
    | '/reports'
    | '/support'
    | '/team'
    | '/trust'
    | '/verification'
    | '/vetting'
    | '/'
    | '/sellers/$sellerId'
    | '/sellers'
  id:
    | '__root__'
    | '/_console'
    | '/sign-in'
    | '/_console/catalogue'
    | '/_console/delivery'
    | '/_console/disputes'
    | '/_console/finance'
    | '/_console/integrations'
    | '/_console/on-call'
    | '/_console/orders'
    | '/_console/pilot'
    | '/_console/privacy'
    | '/_console/profile'
    | '/_console/provinces'
    | '/_console/reports'
    | '/_console/support'
    | '/_console/team'
    | '/_console/trust'
    | '/_console/verification'
    | '/_console/vetting'
    | '/_console/'
    | '/_console/sellers/$sellerId'
    | '/_console/sellers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ConsoleRoute: typeof ConsoleRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_console': {
      id: '/_console'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/': {
      id: '/_console/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/catalogue': {
      id: '/_console/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof ConsoleCatalogueRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/delivery': {
      id: '/_console/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof ConsoleDeliveryRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/disputes': {
      id: '/_console/disputes'
      path: '/disputes'
      fullPath: '/disputes'
      preLoaderRoute: typeof ConsoleDisputesRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/finance': {
      id: '/_console/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof ConsoleFinanceRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/integrations': {
      id: '/_console/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof ConsoleIntegrationsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/on-call': {
      id: '/_console/on-call'
      path: '/on-call'
      fullPath: '/on-call'
      preLoaderRoute: typeof ConsoleOnCallRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/orders': {
      id: '/_console/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof ConsoleOrdersRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/pilot': {
      id: '/_console/pilot'
      path: '/pilot'
      fullPath: '/pilot'
      preLoaderRoute: typeof ConsolePilotRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/privacy': {
      id: '/_console/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof ConsolePrivacyRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/profile': {
      id: '/_console/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ConsoleProfileRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/provinces': {
      id: '/_console/provinces'
      path: '/provinces'
      fullPath: '/provinces'
      preLoaderRoute: typeof ConsoleProvincesRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/reports': {
      id: '/_console/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ConsoleReportsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/support': {
      id: '/_console/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof ConsoleSupportRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/team': {
      id: '/_console/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof ConsoleTeamRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/trust': {
      id: '/_console/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof ConsoleTrustRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/verification': {
      id: '/_console/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof ConsoleVerificationRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/vetting': {
      id: '/_console/vetting'
      path: '/vetting'
      fullPath: '/vetting'
      preLoaderRoute: typeof ConsoleVettingRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/sellers/': {
      id: '/_console/sellers/'
      path: '/sellers'
      fullPath: '/sellers/'
      preLoaderRoute: typeof ConsoleSellersIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/sellers/$sellerId': {
      id: '/_console/sellers/$sellerId'
      path: '/sellers/$sellerId'
      fullPath: '/sellers/$sellerId'
      preLoaderRoute: typeof ConsoleSellersSellerIdRouteImport
      parentRoute: typeof ConsoleRoute
    }
  }
}

interface ConsoleRouteChildren {
  ConsoleCatalogueRoute: typeof ConsoleCatalogueRoute
  ConsoleDeliveryRoute: typeof ConsoleDeliveryRoute
  ConsoleDisputesRoute: typeof ConsoleDisputesRoute
  ConsoleFinanceRoute: typeof ConsoleFinanceRoute
  ConsoleIntegrationsRoute: typeof ConsoleIntegrationsRoute
  ConsoleOnCallRoute: typeof ConsoleOnCallRoute
  ConsoleOrdersRoute: typeof ConsoleOrdersRoute
  ConsolePilotRoute: typeof ConsolePilotRoute
  ConsolePrivacyRoute: typeof ConsolePrivacyRoute
  ConsoleProfileRoute: typeof ConsoleProfileRoute
  ConsoleProvincesRoute: typeof ConsoleProvincesRoute
  ConsoleReportsRoute: typeof ConsoleReportsRoute
  ConsoleSupportRoute: typeof ConsoleSupportRoute
  ConsoleTeamRoute: typeof ConsoleTeamRoute
  ConsoleTrustRoute: typeof ConsoleTrustRoute
  ConsoleVerificationRoute: typeof ConsoleVerificationRoute
  ConsoleVettingRoute: typeof ConsoleVettingRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
  ConsoleSellersSellerIdRoute: typeof ConsoleSellersSellerIdRoute
  ConsoleSellersIndexRoute: typeof ConsoleSellersIndexRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleCatalogueRoute: ConsoleCatalogueRoute,
  ConsoleDeliveryRoute: ConsoleDeliveryRoute,
  ConsoleDisputesRoute: ConsoleDisputesRoute,
  ConsoleFinanceRoute: ConsoleFinanceRoute,
  ConsoleIntegrationsRoute: ConsoleIntegrationsRoute,
  ConsoleOnCallRoute: ConsoleOnCallRoute,
  ConsoleOrdersRoute: ConsoleOrdersRoute,
  ConsolePilotRoute: ConsolePilotRoute,
  ConsolePrivacyRoute: ConsolePrivacyRoute,
  ConsoleProfileRoute: ConsoleProfileRoute,
  ConsoleProvincesRoute: ConsoleProvincesRoute,
  ConsoleReportsRoute: ConsoleReportsRoute,
  ConsoleSupportRoute: ConsoleSupportRoute,
  ConsoleTeamRoute: ConsoleTeamRoute,
  ConsoleTrustRoute: ConsoleTrustRoute,
  ConsoleVerificationRoute: ConsoleVerificationRoute,
  ConsoleVettingRoute: ConsoleVettingRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
  ConsoleSellersSellerIdRoute: ConsoleSellersSellerIdRoute,
  ConsoleSellersIndexRoute: ConsoleSellersIndexRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ConsoleRoute: ConsoleRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
