#!/usr/bin/env node
// Regenerates the web apps' static legal pages from the design (CLAUDE.md: ship 09 Terms of Service and 10 Privacy
// Policy verbatim, opened from registration in a new tab). Keeps the design's markup and copy, drops the prototype
// runtime (support.js, <x-dc>/<helmet>, icon font) and links the Northline stylesheet.
//
//   node scripts/legal-pages.mjs [out-dir]
//
// S-63: one copy in web/packages/legal/pages, served at /legal/ by the Studio and the consumer app (its Vite plugin);
// web/packages/legal's test checks the committed files are this script's output.
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outs = [process.argv[2] ?? join(root, 'web/packages/legal/pages')];
for (const out of outs) {
  mkdirSync(out, { recursive: true });
  copyFileSync(join(root, 'design/theme/northline.css'), join(out, 'northline.css'));
}

const pages = [
  { src: '09 Terms of Service.dc.html', dest: 'terms.html', title: 'Terms of Service · Northline' },
  { src: '10 Privacy Policy.dc.html', dest: 'privacy.html', title: 'Privacy Policy · Northline' },
];
const links = [['09 Terms of Service.dc.html', 'terms.html'], ['10 Privacy Policy.dc.html', 'privacy.html']];

for (const page of pages) {
  const html = readFileSync(join(root, 'design', page.src), 'utf8');
  const helmet = html.slice(html.indexOf('<helmet>') + 8, html.indexOf('</helmet>'));
  const style = helmet.match(/<style>([\s\S]*?)<\/style>/)?.[1] ?? '';
  let body = html.slice(html.indexOf('</helmet>') + 9, html.lastIndexOf('</x-dc>')).trim();
  for (const [from, to] of links) body = body.split(from).join(to);
  const lang = 'en-CA';
  const file = `<!doctype html>
<!-- Generated by scripts/legal-pages.mjs from design/${page.src} — do not edit by hand. -->
<html lang="${lang}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${page.title}</title>
<link rel="stylesheet" href="northline.css">
<style>${style}
/* Phones: one column, no sticky contents, no horizontal scroll at 320 px. */
@media (max-width: 720px) {
  body > div > div { grid-template-columns: minmax(0, 1fr) !important; }
  aside { position: static !important; margin-bottom: 24px; }
}
</style>
</head>
<body>
${body}
</body>
</html>
`;
  for (const out of outs) {
    writeFileSync(join(out, page.dest), file);
    console.log(`wrote ${join(out, page.dest)}`);
  }
}
